[[redirects]]
  from = "/search"
  to = "https://api.mysearch.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/*"
  to = "/dashboard"
  status = 200
  force = false
  query = {path = ":path"} # apply this rule for /?path=example
  conditions = {Role = ["admin"]}
      
[[redirects]]
  from = "/*"
  to = "/login"
  status = 302